repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier --write --ignore-unknown --log-level warn --no-error-on-unmatched-pattern
        language: system
        types_or: [javascript, css, scss, html, json]
        pass_filenames: true