services:
  db:
    image: postgres:18-alpine
    container_name: cinetagit_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-cinetagit}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpassword}
      POSTGRES_DB: ${POSTGRES_DB:-cinetagit_db}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - cinetagit_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-cinetagit} -d ${POSTGRES_DB:-cinetagit_db}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: cinetagit_redis
    restart: always
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --appendonly yes
    volumes:
      - ./data/redis:/data
    networks:
      - cinetagit_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    image: ghcr.io/imanuelbertrand/cinetag.it:latest
    container_name: cinetagit_app
    restart: always
    expose:
      - "8000"
    environment:
      - DATABASE_URI=postgresql://${POSTGRES_USER:-cinetagit}:${POSTGRES_PASSWORD:-secretpassword}@db:5432/${POSTGRES_DB:-cinetagit_db}
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - SERVER_NAME=${SERVER_NAME}
      - APPLICATION_ROOT=${APPLICATION_ROOT}
      - PREFERRED_URL_SCHEME=${PREFERRED_URL_SCHEME}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT:-587}
      - MAIL_USE_TLS=${MAIL_USE_TLS:-true}
      - MAIL_USE_SSL=${MAIL_USE_SSL:-false}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
      - MAIL_DEFAULT_SENDER_NAME=${MAIL_DEFAULT_SENDER_NAME}
      - JWT_ACCESS_TOKEN_EXPIRES=${JWT_ACCESS_TOKEN_EXPIRES:-3600}
      - JWT_REFRESH_TOKEN_EXPIRES=${JWT_REFRESH_TOKEN_EXPIRES:-604800}
      - DEFAULT_REGION=${DEFAULT_REGION:-US}
      - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE:-en}
      - CACHE_TYPE=RedisCache
      - CACHE_REDIS_URL=redis://redis:6379/0
      - CACHE_DEFAULT_TIMEOUT=${CACHE_DEFAULT_TIMEOUT:-300}
      - INSTANCE_PATH=/app/instance
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./data/storage:/app/storage
      - ./data/instance:/app/instance
    networks:
      - cinetagit_network

  nginx:
    image: ghcr.io/imanuelbertrand/cinetag.it-nginx:latest
    container_name: cinetagit_nginx
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/storage/posters:/usr/share/nginx/html/posters:ro
    depends_on:
      - web
    networks:
      - cinetagit_network

networks:
  cinetagit_network:
    driver: bridge
