services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: cinetagit_mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    networks:
      - cinetagit_network

  web:
    environment:
      - MAIL_SERVER=mailhog
      - MAIL_PORT=1025
      - MAIL_USE_TLS=false
      - MAIL_USE_SSL=false
      - SERVER_NAME=${SERVER_NAME:-localhost:8000}
      - PREFERRED_URL_SCHEME=${PREFERRED_URL_SCHEME:-http}
      - MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER:-noreply@cinetag.it}
    depends_on:
      - mailhog
