version: '3.8'

services:
  web:
    # Use the root Dockerfile for the dev environment
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/app:cached
      - app_logs:/app/app/logs
      - app_storage:/app/storage
    environment:
      - FLASK_ENV=development
      - DATABASE_URI=postgresql://${POSTGRES_USER:-cinetagit}:${POSTGRES_PASSWORD:-secretpassword}@db:5432/${POSTGRES_DB:-cinetagit_db}
      # Overwrite the default entrypoint to start in development mode
      - FLASK_APP=app.create_app:create_app('development',start_scheduler=True)
      - CACHE_TYPE=RedisCache
      - CACHE_REDIS_URL=redis://redis:6379/0
      - CACHE_DEFAULT_TIMEOUT=300
    # Override the root entrypoint for development
    entrypoint: []
    command: ["flask", "run", "--host=0.0.0.0", "--port=8000"]
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailhog:
        condition: service_started

  mailhog:
    container_name: cinetagit-mailhog
    image: mailhog/mailhog
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP server

volumes:
  app_logs:
  app_storage:

networks:
  cinetagit_network:
    driver: bridge
